[package]
name = "flying-dutchman"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chess = "3.2.0"
circular-buffer = "0.1.9"
logos = "0.15.0"
lru = "0.12.5"
nohash-hasher = "0.2.0"
uci = "0.2.3"
